// GET MOVIE
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

// GET MOVIE DETAIL
export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAIL = "GET_MOVIE_DETAILS_FAIL";
export const GET_MOVIE_DETAILS_RESET = "GET_MOVIE_DETAILS_RESET";

// Counter
export const GET_COUNTER_REQUEST = "GET_COUNTER_REQUEST";
export const GET_COUNTER_INCREASE = "GET_COUNTER_INCREASE";
export const GET_COUNTER_DECREASE = "GET_COUNTER_DECREASE";
export const GET_COUNTER_FAIL = "GET_COUNTER_FAIL";

// payment
export const CHECK_OUT_REQUEST = "CHECK_OUT_REQUEST";
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS";
export const CHECK_OUT_FAIL = "CHECK_OUT_FAIL";
export const CHECK_OUT_RESET = "CHECK_OUT_RESET";

// BOOKING SHOW
export const GET_BOOKING_REQUEST = "GET_BOOKING_REQUEST";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAIL = "GET_BOOKING_FAIL";
export const GET_BOOKING_RESET = "GET_BOOKING_RESET";

// history booking
export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAIL = "GET_HISTORY_FAIL";
export const GET_HISTORY_RESET = "GET_HISTORY_RESET";

// waitting booking
export const GET_WAITTING_HISTORY_REQUEST = "GET_WAITTING_HISTORY_REQUEST";
export const GET_WAITTING_HISTORY_SUCCESS = "GET_WAITTING_HISTORY_SUCCESS";
export const GET_WAITTING_HISTORY_FAIL = "GET_WAITTING_HISTORY_FAIL";
export const GET_WAITTING_HISTORY_RESET = "GET_WAITTING_HISTORY_RESET";

// booker history
export const GET_BOOKED_HISTORY_REQUEST = "GET_BOOKED_HISTORY_REQUEST";
export const GET_BOOKED_HISTORY_SUCCESS = "GET_BOOKED_HISTORY_SUCCESS";
export const GET_BOOKED_HISTORY_FAIL = "GET_BOOKED_HISTORY_FAIL";
export const GET_BOOKED_HISTORY_RESET = "GET_BOOKED_HISTORY_RESET";
