// GET MOVIE
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

// GET MOVIE DETAIL
export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAIL = "GET_MOVIE_DETAILS_FAIL";
export const GET_MOVIE_DETAILS_RESET = "GET_MOVIE_DETAILS_RESET";

// Counter
export const GET_COUNTER_REQUEST = "GET_COUNTER_REQUEST";
export const GET_COUNTER_INCREASE = "GET_COUNTER_INCREASE";
export const GET_COUNTER_DECREASE = "GET_COUNTER_DECREASE";
export const GET_COUNTER_FAIL = "GET_COUNTER_FAIL";

// payment
export const CHECK_OUT_REQUEST = "CHECK_OUT_REQUEST";
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS";
export const CHECK_OUT_FAIL = "CHECK_OUT_FAIL";
export const CHECK_OUT_RESET = "CHECK_OUT_RESET";
