// GET CINEMA
export const GET_CINEMA_REQUEST = "GET_CINEMA_REQUEST";
export const GET_CINEMA_SUCCESS = "GET_CINEMA_SUCCESS";
export const GET_CINEMA_FAIL = "GET_CINEMA_FAIL";

// GET CINEMA DETAIL
export const GET_CINEMA_DETAILS_REQUEST = "GET_CINEMA_DETAILS_REQUEST";
export const GET_CINEMA_DETAILS_SUCCESS = "GET_CINEMA_DETAILS_SUCCESS";
export const GET_CINEMA_DETAILS_FAIL = "GET_CINEMA_DETAILS_FAIL";
export const GET_CINEMA_DETAILS_RESET = "GET_CINEMA_DETAILS_RESET";

// GET SCHEDULE
export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAIL = "GET_SCHEDULE_FAIL";

// GET SCHEDULE DETAIL
export const GET_SCHEDULE_DETAILS_REQUEST = "GET_SCHEDULE_DETAILS_REQUEST";
export const GET_SCHEDULE_DETAILS_SUCCESS = "GET_SCHEDULE_DETAILS_SUCCESS";
export const GET_SCHEDULE_DETAILS_FAIL = "GET_SCHEDULE_DETAILS_FAIL";
export const GET_SCHEDULE_DETAILS_RESET = "GET_SCHEDULE_DETAILS_RESET";

// Counter
export const GET_COUNTER_REQUEST = "GET_COUNTER_REQUEST";
export const GET_COUNTER_INCREASE = "GET_COUNTER_INCREASE";
export const GET_COUNTER_DECREASE = "GET_COUNTER_DECREASE";
export const GET_COUNTER_FAIL = "GET_COUNTER_FAIL";
