// GET CINEMA
export const GET_CINEMA_REQUEST = "GET_CINEMA_REQUEST";
export const GET_CINEMA_SUCCESS = "GET_CINEMA_SUCCESS";
export const GET_CINEMA_FAIL = "GET_CINEMA_FAIL";

// GET CINEMA DETAIL
export const GET_CINEMA_DETAILS_REQUEST = "GET_CINEMA_DETAILS_REQUEST";
export const GET_CINEMA_DETAILS_SUCCESS = "GET_CINEMA_DETAILS_SUCCESS";
export const GET_CINEMA_DETAILS_FAIL = "GET_CINEMA_DETAILS_FAIL";
export const GET_CINEMA_DETAILS_RESET = "GET_CINEMA_DETAILS_RESET";

export const GET_CINEMA_DETAILS_REQUEST_SHOWTIME = "GET_CINEMA_DETAILS_REQUEST_SHOWTIME";
export const GET_CINEMA_DETAILS_SUCCESS_SHOWTIME = "GET_CINEMA_DETAILS_SUCCESS_SHOWTIME";
export const GET_CINEMA_DETAILS_FAIL_SHOWTIME = "GET_CINEMA_DETAILS_FAIL_SHOWTIME";

// GET SCHEDULE
export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAIL = "GET_SCHEDULE_FAIL";

// GET SCHEDULE DETAIL
export const GET_SCHEDULE_DETAILS_REQUEST = "GET_SCHEDULE_DETAILS_REQUEST";
export const GET_SCHEDULE_DETAILS_SUCCESS = "GET_SCHEDULE_DETAILS_SUCCESS";
export const GET_SCHEDULE_DETAILS_FAIL = "GET_SCHEDULE_DETAILS_FAIL";
export const GET_SCHEDULE_DETAILS_RESET = "GET_SCHEDULE_DETAILS_RESET";

// Showtime
export const GET_SHOWTIME_REQUEST = "GET_SHOWTIME_REQUEST";
export const GET_SHOWTIME_SUCCESS = "GET_SHOWTIME_SUCCESS";
export const GET_SHOWTIME_FAIL = "GET_SHOWTIME_FAIL";
// Movie
export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";

// Delete
export const GET_DELETE_REQUEST = "GET_DELETE_REQUEST";
export const GET_DELETE_SUCCESS = "GET_DELETE_SUCCESS";
export const GET_DELETE_FAIL = "GET_DELETE_FAIL";

//login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
